### Get the secret ingredient.
GET https://localhost:5091/secret/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hcmtqIiwic3ViIjoibWFya2oiLCJqdGkiOiI0MmNhODYzYSIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUxMzEiLCJodHRwczovL2xvY2FsaG9zdDo1MDkxIiwiaHR0cDovL2xvY2FsaG9zdDo1MDkwIl0sIm5iZiI6MTc1MDUwMzUwMSwiZXhwIjoxNzU4NDUyMzAxLCJpYXQiOjE3NTA1MDM1MDIsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.1kIIdfZdTd_2KJBaLcAw3wuXnrr4xqGoBjjLaosTWgI
